### ISSUE TITLE
ScrollTo functionality

### ISSUE THREAD

**Issue by cda210** [dgreene1/react-accessible-treeview#107]
Note: For large trees - would be nice to have ability to scrollTo a specific node - see behavior from antD Tree - 

https://ant.design/components/tree#tree-methods

**Describe the solution you'd like**
A method on the tree instance that allows developers to programmatically scroll to a specific node and align accordingly.

**What value does this proposed solution bring to users?**
When auto-selecting - like after a search - allows the tree to focus on the selected node
Displaying a large tree with selections - allows developers to focus on the actual selected value vs user having to manually find previously selected nodes. 

**Describe alternatives you've considered**
Custom event to scroll using document.querySelector or scrollIntoView()

**Comment by dgreene1** [comment]
@cda210. Hi Chris, since this is a request from internal to our company, can you please file an RFA request and then have our PM prioritize it by talking to your PM? In the meantime, I’m going to close this issue since active issue counts are seen by potential consumers as a negative. So we try to keep them low. If your internal JIRA ticket is approved then we’ll reopen this issue here when the PR is worked. We want to keep the RFA process for Vertex <—> Vertex the same.

**Comment by hnnweb** [comment]
@dgreene1 since this is marked as completed, where is this documented? How can we use this functionality?

**Comment by dgreene1** [comment]
@hnnweb this issue was closed as not completed. If you’d like it to be completed, tell me and I can reopen it. But I’d only reopen it if it’s something you or your team would be interested in building since it’s not a priority for our team.

**Comment by hnnweb** [comment]
> @hnnweb this issue was closed as not completed. If you’d like it to be completed, tell me and I can reopen it. But I’d only reopen it if it’s something you or your team would be interested in building since it’s not a priority for our team.

No, you closed it as "completed"

![image](https://github.com/dgreene1/react-accessible-treeview/assets/3874960/dbb11deb-d4e6-4e05-b070-b3e1a11266b9)

I am interested in the result of the ticket since it is here. What are the result in Jira, since you have one public and one private ticket system and basically prioritizing your own needs and not the community.
That is the reflection i have by reading the issues here.

I can be wrong, but that is my reflection...

**Comment by hgodinho** [comment]
sooo, this won't be implemented?

**Comment by dgreene1** [comment]
@hgodinho See comment https://github.com/dgreene1/react-accessible-treeview/issues/107#issuecomment-1845362722

We’re open to contributions.

> I am interested in the result of the ticket since it is here. What are the result in Jira, since you have one public and one private ticket system and basically prioritizing your own needs and not the community.
That is the reflection i have by reading the issues here. I can be wrong, but that is my reflection...

@hnnweb we prioritize features that improve the accessibility of the existing functionality. New functionality has less priority. That’s especially true of functionality like the one proposed in this issue where the accessibility impacts are unclear and there is not a well documented solution in the WCAG. I hope that this explanation of our prioritization process gave you helpful insight. This is volunteerism and therefore we have to be judicious about which features are most helpful and which features won’t increase the overall maintenance requirements. For futher context, we took over this repo from a previous owner who had abandoned it, so I hope it’s clear that we very much do care about the community since without us this would be an abandoned repo with countless open security holes.

**Comment by hgodinho** [comment]
I could try a PR, but as I'm using it for a [personal project](https://hgod.in/cv) I can't guarantee a rush on it. 

Do you have any suggested approach?

**Comment by dgreene1** [comment]
I do not. I personally wouldn’t use a tree this type of thing. I’d probably use a table with a filter.
