### ISSUE TITLE
flattenTree function doesn't persist isBranch property

### ISSUE THREAD

**Issue by sandro768** [dgreene1/react-accessible-treeview#122]
**Describe the bug**
I'm trying to use isBranch property inside flattenTree function but it's doesn't persist

**To Reproduce**
Try to execute a function with an object that has isBranch property

**Comment by dgreene1** [comment]
Closing since this is a duplicate of #86. Once https://github.com/dgreene1/react-accessible-treeview/pull/117 is merged you’ll be able to set that prop on the metadata object.

**Comment by dgreene1** [comment]
Released in https://github.com/dgreene1/react-accessible-treeview/releases/tag/v2.6.0

**Comment by hnnweb** [comment]
This should be opened again since it doesn't solve the problem.

What I can see #117 preserves the metadata. But `isBranch` is not part of metadata according to the [API Reference](https://dgreene1.github.io/react-accessible-treeview/docs/api#data).

I'm running 2.8.0 and flattenTree removes isBranch from the JSON object.

**Comment by dgreene1** [comment]
@hnnweb would you consider submitting a PR now that I’ve reopened the issue?

**Comment by hnnweb** [comment]
The original one from @sandro768 should do it...

**Comment by dgreene1** [comment]
@hnnweb I approved it and merged it, but I’m not sure when the team will be able to release it. Hold tight while I get an answer. Check the release notes since I might forget to update you here.

**Comment by kpustakhod** [comment]
Hey @dgreene1 i see the potential issue in https://github.com/dgreene1/react-accessible-treeview/pull/123. Now tree can display the branch node without any children, please see screenshots below.
The view ('Onion' is set as branch but with children: [] or without children property):
<img width="473" alt="Screenshot 2023-09-14 at 09 10 48" src="https://github.com/dgreene1/react-accessible-treeview/assets/16884481/129ab913-28ae-4b4b-bace-62b8a5451574">
The code:
<img width="473" alt="Screenshot 2023-09-14 at 09 10 43" src="https://github.com/dgreene1/react-accessible-treeview/assets/16884481/76f8f6e1-12b7-4f9e-b500-0c2e619ac647">
<img width="473" alt="Screenshot 2023-09-14 at 09 12 05" src="https://github.com/dgreene1/react-accessible-treeview/assets/16884481/792a0aac-da6d-449d-ae36-d1a637da6cb5">

**Comment by hnnweb** [comment]
@kpustakhod That is the purpose.
If you build the native tree ( with id and parent ) it works like this.

flattenTree didn't take isBranch into the object.

Please see the documentation:
https://dgreene1.github.io/react-accessible-treeview/docs/api#data

**Comment by kpustakhod** [comment]
`flattenTree` didn't take `isBranch` into the object because it is used not only for async functionality. I try to highlight that after https://github.com/dgreene1/react-accessible-treeview/pull/123 those users who use `flattenTree` and don't load data asyncroniously will possibly get a broken tree view if somehow they've set isBranch prop in object that is passed to `flattenTree`.
Additionally i would expect some tests are added in`src/__tests__/FlattenTree.test.ts` and async examples in storybook are also updated.

**Comment by mellis481** [comment]
@hnnweb Are you loading data asynchronously?

**Comment by hnnweb** [comment]
@mellis481 Both.
We are displaying a file tree ( As this example https://dgreene1.github.io/react-accessible-treeview/docs/examples-DirectoryTree ).
The isBranch is used to display it as a folder in case it is empty ie. empty children,

Data is loaded asynchronously before the component is loaded but is also populated as data is changed ( removed, added, changed or moved )
