### ISSUE TITLE
Do not lock issues

### ISSUE THREAD

**Issue by baba43** [dgreene1/react-accessible-treeview#153]
I do not like the fact that tickets are locked immediately. This is not only disrespectful, because you no longer allow feedback, but you also prevent a productive exchange within the community. 

In any case, it makes the impression that feedback is unwanted and I think that should not be the case. I wanted to start a discussion on a topic that would also benefit the reach of this library and my ticket was locked after the first reply. I would have more to say about it and besides, the same question could come up to other developers.

I would love to use this library and would also be willing to contribute. 

Thank you and keep up the good work.

**Comment by dgreene1** [comment]
I’m sorry I did that. But we still can’t provide the flexibility you’re asking for without compromising the design goals of the library. I would recommend that you fork.

> I would have more to say about it and besides, the same question could come up to other developers.

Not only do we not have capacity to support this work, but we don’t have capacity to discuss it further. That’s what the “lock as resolved functionality” is for in Github.

I’ll leave comments open as a courtesy this time, but I will close the issue since it’s resolved.

**Comment by baba43** [comment]
I don't mind requests being denied or tickets being closed, but I think it is counterproductive in every way when tickets are locked. However, I just see that most tickets are not locked, just some.

Finally, thanks again for making this project available. I will follow your suggestion and fork it if I get stuck.
