### ISSUE TITLE
collapse/uncollapse all

### ISSUE THREAD

**Issue by Chrisdo82** [dgreene1/react-accessible-treeview#20]
Is there a way to collapse or uncollapse all nodes and their descendants without setting the defaultExpandedIds prop?

**Comment by jossmac** [comment]
This would be great, and could encompass more than the expanded state: I'm imagining something like [downshift's `stateReducer`](https://github.com/downshift-js/downshift#statereducer).

For my case, I need to reset the component's internal state when provided with new data because the expanded nodes become out of sync.

If anyone has a similar requirement, I'm using this hack (other functionality omitted for brevity):

```jsx
import AccessibleTreeView from 'react-accessible-treeview';

export function TreeView({ data }) {
  const [key, setKey] = useState(0);

  // NOTE: requires `data` to be memoized by the consumer
  useEffect(() => {
    setKey((n) => n + 1);
  }, [data]);

  return <AccessibleTreeView key={key} data={data} />
}
```

**Comment by dgreene1** [comment]
The user can do it by pressing the * key from within a screen reader.

Programmatically you’d have to use one of the control props.

I think it might be best to keep “how to” questions to StackOverflow as issues are for bug fixes or feature requests. And in full transparency, we won’t be taking on feature requests unless they are accessibility related since the current API is flexible enough for almost anything.
