### ISSUE TITLE
Visualization of the connections between the tree elements with lines

### ISSUE THREAD

**Issue by techogdev** [dgreene1/react-accessible-treeview#204]
Assume the tree is structured in such a way that there are various nested categories (nodes). Within these, there are x elements (items). In such cases, users might struggle to clearly understand how the nesting looks beyond a certain depth.

**My feature request**
Is it possible to draw a line to visually connect one treeview node or items to another? Perhaps such a function could be controlled via the API, e.g., turned on or off?

**Benefits for the user**
This would make it easier for users to clearly recognize which nodes and items belong together, even in a complex tree structure.

**Example**
![treeview-example](https://github.com/user-attachments/assets/20d65cb5-32f6-4e09-a2fd-3b7957f5ccf4)

**Comment by dgreene1** [comment]
Unless I’m mistaken, this can already be done in CSS, which means that this issue is a stack overflow styled question. We don’t have budget to answer those types of questions.

I’ll reopen this ticket again if you truly can’t solve it on your own, but here’s what I found for you. Please try it and other things you Google. But CSS should let you do it.
https://stackoverflow.com/a/40697360
