### ISSUE TITLE
Add custom properties to element object

### ISSUE THREAD

**Issue by Sp33ktrE** [dgreene1/react-accessible-treeview#53]
Hi, is there a way to add more data to a node object?

**Comment by dgreene1** [comment]
We’ll need more information before we can answer your question.

like what would this extra data look like when it is rendered?

please consider providing a visual mock-up and/or a TypeScript interface for your proposal.

before you do, please look at the interface to see if it’s possible. There is a render function that likely does what you need.

**Comment by Sp33ktrE** [comment]
1) Basically, i want to add more optional data to my node when generating the data tree so i can do conditional styling/behaviour.


![type](https://user-images.githubusercontent.com/76818068/194752069-a1d503c9-dcfa-4a30-92eb-00f57c9dd34e.png)


2) Is there a way to preserve the same node ids when generating a tree using the flattenTree helper function instead of autoincremental ids.

**Comment by dgreene1** [comment]
This isn’t a scenario that I or my team has needed so the only answer I can give is “I don’t know.”

I will share that there is a nodeRenderer function on the component for which you can do a lookup within and then conditionally style each node. The lookup (by name or by ID) will allow you to get everything you need.

I don’t have time to code that out right now.

I think it might be best to keep “how to” questions to StackOverflow as issues are for bug fixes or feature requests. And in full transparency, we won’t be taking on feature requests unless they are accessibility related since the current API is flexible enough for almost anything.
