### ISSUE TITLE
Do not publish src/index.ts to npm

### ISSUE THREAD

**Issue by VinceBT-BG** [dgreene1/react-accessible-treeview#72]
See screenshot, this is after installing with standard npm

<img width="259" alt="Capture d’écran 2022-12-12 à 15 33 13" src="https://user-images.githubusercontent.com/117643868/207071866-4b6c4c9d-8814-45d6-ad3e-4297045bc851.png">

**Comment by dgreene1** [comment]
@VinceBT-BG is this causing a problem for you somehow?

I ask because Webpack and tsc are bringing in only the file in dist since that is what the package.json instructs those tools to do.

So, given that this can’t (from my knowledge) be introducing performance or compilation issues, we will close this as too low priority. We can reopen the issue if you write back with details on how it is negatively impacting you and/or if you decide to send in a PR fixing it.

**Comment by VinceBT-BG** [comment]
It's causing IDE compilation errors but only when the file is opened and weird behavior with auto imports but no big deal.

**Comment by dgreene1** [comment]
Yes, VSCode will show errors if you have different TSConfig rules and if you have it open. But if you search StackOverflow and look in the TSConfig docs you’ll see how to ignore typescript errors in node modules. It’s the recommended behavior. I can’t give more advice on this. Just don’t open the index.ts.
