### ISSUE TITLE
Chose whether we want `focus` or `scrollIntoView` when changing expandedIds

### ISSUE THREAD

**Issue by VinceBT-BG** [dgreene1/react-accessible-treeview#73]
When using an external search bar, the focus gets eaten after changing the expandedIds to show the found items, I am sending an example

**Comment by dgreene1** [comment]
@yhy-1 @mellis481 I leave it to you to determine the priority of this. I’d like to get an issue template added to this repo since it’s burdensome to get bug reports that don’t contain the code or the steps to reproduce. @VinceBT-BG please provide the the code (like the props you sent in) AND the steps to reproduce.

**Comment by VinceBT-BG** [comment]
Here you have a simple example that shows the issue

# Reproduction steps:

- Use this component:
```tsx
import React from 'react'
import TreeView, { INode, flattenTree } from 'react-accessible-treeview'

function flatten<T>(arr: T[][]): T[] {
	return ([] as T[]).concat(...arr)
}

type NestedArray<T> = Array<NestedArray<T> | T>

function flattenDeep<T>(input: NestedArray<T>): T[] {
	return flatten(input.map(x => (Array.isArray(x) ? flattenDeep(x) : [x])))
}

const findParents = (data: INode[], node: INode): number[] => {
	if (!node?.parent) {
		return []
	}
	const parentNode = data?.filter(dataNode => dataNode.id === node?.parent)
	return [node.parent, ...findParents(data, parentNode[0])]
}

const folder = {
	name: '',
	children: [
		{
			name: 'Fruits',
			children: [{ name: 'Avocados' }, { name: 'Bananas' }, { name: 'Berries' }, { name: 'Oranges' }, { name: 'Pears' }],
		},
		{
			name: 'Drinks',
			children: [
				{ name: 'Apple Juice' },
				{ name: 'Chocolate' },
				{ name: 'Coffee' },
				{
					name: 'Tea',
					children: [{ name: 'Black Tea' }, { name: 'Green Tea' }, { name: 'Red Tea' }, { name: 'Matcha' }],
				},
			],
		},
		{
			name: 'Vegetables',
			children: [{ name: 'Beets' }, { name: 'Carrots' }, { name: 'Celery' }, { name: 'Lettuce' }, { name: 'Onions' }],
		},
	],
}

const data = flattenTree(folder)

export const SearchTree = () => {
	const [expandedIds, setExpandedIds] = React.useState<number[]>([])
	const [searchValue, setSearchValue] = React.useState<string>('')

	const [hiddenIds, setHiddenIds] = React.useState<number[]>([])

	const allIds = React.useMemo(() => data.map(element => element.id), [])

	React.useEffect(() => {
		if (!searchValue) {
			setHiddenIds([])
			return
		}
		// Filter elements containing part of search value
		const searchResult = data.filter(element => element.name.toLowerCase().includes(searchValue.toLowerCase()))
		// For each result, find all parents and flatten array
		const parents = flattenDeep(searchResult.map(result => findParents(data, result)))
		// Expand parents without changing the already expanded elements
		const nextExpandedIds = [...new Set([...expandedIds, ...parents]).values()]
		if (JSON.stringify(expandedIds) !== JSON.stringify(nextExpandedIds)) {
			setExpandedIds(nextExpandedIds)
		}
		const allChildren = flatten(searchResult.map(node => [...node.children]))
		const idsToShow = [...parents, ...searchResult.map(el => el.id), ...allChildren]
		setHiddenIds(allIds.filter(id => !idsToShow.includes(id)))
	}, [allIds, expandedIds, searchValue])

	return (
		<>
			<input placeholder="Enter a for example" onChange={event => setSearchValue(event?.target.value)} style={{ border: '1px solid red' }}></input>
			<TreeView
				data={data}
				expandedIds={expandedIds}
				nodeRenderer={({ element, isBranch, getNodeProps, level, handleExpand }) => {
					return (
						<div
							{...getNodeProps({ onClick: handleExpand })}
							style={{ marginLeft: 40 * (level - 1), ...(hiddenIds.includes(element.id) ? { display: 'none' } : {}) }}
						>
							{isBranch && '>'}
							<span style={{ userSelect: 'none' }}>{element.name}</span>
						</div>
					)
				}}
			/>
		</>
	)
}
```

- You get this visual:
<img width="224" alt="Capture d’écran 2022-12-12 à 16 49 28" src="https://user-images.githubusercontent.com/117643868/207090385-ae8e3145-dcaa-48f7-85cd-c52bc54eff64.png">

- You press the letter "a" inside the input

# Expected results

You can still type inside the input to continue the search

# Actual results

The focus gets stolen by the last element that matches the search

# Demo

![2022-12-12 16 51 56](https://user-images.githubusercontent.com/117643868/207090993-22605c86-b685-47e4-889e-39806e8b6173.gif)

**Comment by dgreene1** [comment]
We need better reproduction steps.

typically people send us “reproduction steps,” “expected results,” and “actual results.”

**Comment by VinceBT-BG** [comment]
I have updated my message, is this ok for you ?

**Comment by dgreene1** [comment]
Thank you for taking the time to document this. Now that I can see what you were looking to do, I can tell you that your proposed enhancement is (a) outside of the scope of work that my team can provide and (b) is problematic enhancement since it would change the way that the screen reader shortcuts are meant to work. 

Instead, please direct your users to use the default search functionality that already exists inside the component.

>  Type a character* | Focus moves to the next node with a name that starts with the typed character. If multiple characters are typed in rapid succession, focus moves to the next node with a name that starts with the string of characters typed.

This is taken from https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role#keyboard_interactions which is what the widget was programmed to follow.

**Comment by VinceBT-BG** [comment]
Your solution does not expand folders that contain elements matching the searched value

**Comment by dgreene1** [comment]
Thank you for clarifying. I’ll reopen this so that you or someone else can PR the library. To be clear, we won’t support a search solution outside of component. So if you want to PR the library to search within the children/folders then we would appreciate the contribution. Our team however does not have capacity at this time.
