### ISSUE TITLE
Question: Select any node through function call

### ISSUE THREAD

**Issue by vyvu99** [dgreene1/react-accessible-treeview#94]
Is there a way to select any node through a function call where the parent nodes will automatically expand, and that node will be selected?

Something look like this: `treeRef.dispatchAction({type: 'SELECT', id: 15});`?

**Comment by dgreene1** [comment]
I’m afraid to say that I honestly don’t know. As an open source project with no funding, that’s not a question we can answer quickly. So what I’d recommend is that you look through the published API and see if there is. If there isn’t, you can open a feature request issue. Please use the feature request template next time so that we better understand your proposal and desired outcome.

In addition to the usual feature request template items that you deleted when making this issue, please provide a link to another tree component that provides a similar API to what you’re asking for.

**Comment by vyvu99** [comment]
@dgreene1 Done, I just use controlled properties, thanks:
```
selectedIds={typeof selectedId === 'number' ? [selectedId] : []}
expandedIds={expandedIds?.length ? expandedIds : []}
```

**Comment by dgreene1** [comment]
I’m glad you found a solution. :)
